finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

finalproject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUpClassView.as_view(), name="signup"),
    path("signout/", views.SignOutClassView.as_view(), name="signout"),
    path("signin/", views.SignInClassView.as_view(), name="signin"),
    path(
        "segmentation/summary/",
        views.SegmentationSummaryClassView.as_view(),
        name="segmentation_summary",
    ),
    path(
        "segmentation/delete/<int:pk>/",
        views.SegmentationDeleteClassView.as_view(),
        name="segmentation_delete",
    ),
    path(
        "segmentation/detail/<int:pk>/",
        views.SegmentationDetailClassView.as_view(),
        name="segmentation_detail",
    ),
    path("segmentation/", views.SegmentationClassView.as_view(), name="segmentation"),
    path("setting/", views.SettingClassView.as_view(), name="setting"),
    path(
        "report/summary/", views.ReportSummaryClassView.as_view(), name="report_summary"
    ),
    path(
        "report/segmentation/",
        views.ReportSegmentationClassView.as_view(),
        name="report_segmentation",
    ),
    path(
        "report/export/report/",
        views.ReportExportReportClassView.as_view(),
        name="report_export_report",
    ),
    path(
        "report/export/image/<int:pk>/",
        views.ReportExportImageClassView.as_view(),
        name="report_export_image",
    ),
    path("report/", views.ReportClassView.as_view(), name="report"),
    path(
        "preference/setting/",
        views.PreferenceSettingClassView.as_view(),
        name="preference_setting",
    ),
    path("preference/", views.PreferenceClassView.as_view(), name="preference"),
    path(
        "manage/user/reset-password/<int:pk>/",
        views.ManageUserResetPasswordClassView.as_view(),
        name="manage_user_reset_password",
    ),
    path(
        "manage/user/group/edit/<int:pk>/",
        views.ManageUserGroupEditClassView.as_view(),
        name="manage_user_group_edit",
    ),
    path(
        "manage/user/edit/<int:pk>/",
        views.ManageUserEditClassView.as_view(),
        name="manage_user_edit",
    ),
    path(
        "manage/user/detail/<int:pk>/",
        views.ManageUserDetailClassView.as_view(),
        name="manage_user_detail",
    ),
    path(
        "manage/user/delete/<int:pk>/",
        views.ManageUserDeleteClassView.as_view(),
        name="manage_user_delete",
    ),
    path(
        "manage/user/add/",
        views.ManageUserAddClassView.as_view(),
        name="manage_user_add",
    ),
    path("manage/user/", views.ManageUsersClassView.as_view(), name="manage_user"),
    path(
        "image/uploader/<str:uploader>/",
        views.ImageUploaderView.as_view(),
        name="image_uploader",
    ),
    path("image/upload/", views.ImageUploadView.as_view(), name="image_upload"),
    path(
        "image/update/<int:pk>/", views.ImageUpdateView.as_view(), name="image_update"
    ),
    path("image/summary/", views.ImageSummaryView.as_view(), name="image_summary"),
    path(
        "image/table/color/",
        views.ImageTableColorClassView.as_view(),
        name="image_table_color",
    ),
    path(
        "image/graph/color/",
        views.ImageGraphColorClassView.as_view(),
        name="image_graph_color",
    ),
    path("image/graph/", views.ImageGraphClassView.as_view(), name="image_graph"),
    path(
        "image/delete/<int:pk>/", views.ImageDeleteView.as_view(), name="image_delete"
    ),
    path(
        "image/detail/<int:pk>/", views.ImageDetailView.as_view(), name="image_detail"
    ),
    path("image/", views.ImageListView.as_view(), name="image_list"),
    path("help/", views.HelpClassView.as_view(), name="help"),
    path("docs/", views.DocsClassView.as_view(), name="docs"),
    path("dashboard/", views.DashboardClassView.as_view(), name="dashboard"),
    path("contact/", views.ContactClassView.as_view(), name="contact"),
    path("blog/", views.BlogClassView.as_view(), name="blog"),
    path(
        "account/profile/",
        views.AccountProfileClassView.as_view(),
        name="account_profile",
    ),
    path(
        "account/<str:username>/update/",
        views.AccountUpdateClassView.as_view(),
        name="account_update",
    ),
    path(
        "account/<str:username>/change-password/",
        views.AccountChangePasswordClassView.as_view(),
        name="account_change_password",
    ),
    path("account/<str:username>/", views.AccountClassView.as_view(), name="account"),
    path("about/", views.AboutClassView.as_view(), name="about"),
    path("", views.IndexClassView.as_view(), name="index"),
]

finalproject/myapp/forms.py
from django import forms
from .models import Image
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError

# models User
from django.contrib.auth.models import User, Group

# models UserProfile
from myapp.models import UserProfile


class ManageUserGroupEditForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = User
        fields = []


class UserResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

        labels = {
            "username": "Username",
            "email": "Email",
        }


class UserForm(forms.ModelForm):
    bio = forms.CharField(label="Bio", required=False)
    phone_number = forms.CharField(label="Phone Number", required=False)
    address = forms.CharField(label="Address", required=False)
    date_of_birth = forms.DateField(label="Date of Birth", required=False)
    profile_pic = forms.ImageField(label="Profile Picture", required=False)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

        labels = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
        }


class UserChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        label="Old Password", widget=forms.PasswordInput(), required=True
    )
    new_password = forms.CharField(
        label="New Password", widget=forms.PasswordInput(), required=True
    )
    confirm_password = forms.CharField(
        label="Confirm New Password", widget=forms.PasswordInput(), required=True
    )

    class Meta:
        model = User
        fields = []

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get("old_password")
        cleaned_data["password"] = old_password
        return cleaned_data


class VisibleMultipleHiddenInput(forms.widgets.HiddenInput):
    def render(self, name, value, attrs=None, renderer=None):
        if not attrs:
            attrs = {}
        attrs["type"] = "hidden"  # Change the input type to 'hidden'
        return mark_safe(super().render(name, value, attrs, renderer))


class ImageForm(forms.ModelForm):
    def clean_image(self):
        image = self.cleaned_data.get("image")
        if not image:
            raise ValidationError(self.error_messages["image"])
        return image

    class Meta:
        model = Image
        fields = [
            "uploader",
            "image",
            "distance",
            "color",
        ]
        labels = {
            "uploader": "Uploader",
            "image": "Image",
            "distance": "Distance",
            "color": "Color",
        }
        widgets = {
            "uploader": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Uploader",
                }
            ),
            "image": forms.FileInput(
                attrs={
                    # tailwindcss
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Image",
                    "id": "id_image",
                    "accept": "image/*",
                }
            ),
            "distance": forms.NumberInput(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Distance",
                    "min": 0,
                    "max": 100,
                    "step": 1,
                }
            ),
            "color": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Color",
                    "data-live-search": "true",
                    "data-size": "5",
                }
            ),
        }
        allow_empty_file = False
        error_messages = {
            "uploader": {
                "required": "Uploader is required but hidden",
            },
            "image": {
                "required": "Image is required but hidden",
            },
        }

finalproject/myapp/views.py
from myapp.myviews.manage_views import (
    ManageClassView,
    ManageUsersClassView,
)

from myapp.myviews.manage_user_views import (
    ManageUserAddClassView,
    ManageUserDeleteClassView,
    ManageUserDetailClassView,
    ManageUserEditClassView,
    ManageUserResetPasswordClassView,
    ManageUserGroupEditClassView,
)

from myapp.myviews.report_views import (
    ReportClassView,
    ReportExportImageClassView,
    ReportExportReportClassView,
    ReportSegmentationClassView,
    ReportSummaryClassView,
)

from myapp.myviews.segmentation_views import (
    SegmentationClassView,
    SegmentationDetailClassView,
    SegmentationSummaryClassView,
    SegmentationDeleteClassView,
)

from myapp.myviews.system_views import (
    SignInClassView,
    SignOutClassView,
    SignUpClassView,
)

from myapp.myviews.preference_views import (
    PreferenceClassView,
    AboutClassView,
    BlogClassView,
    ContactClassView,
    PreferenceSettingClassView,
    HelpClassView,
    DocsClassView,
    SettingClassView,
    DashboardClassView,
    IndexClassView,
)

from myapp.myviews.account_views import (
    AccountChangePasswordClassView,
    AccountClassView,
    AccountUpdateClassView,
    AccountProfileClassView,
)

from myapp.myviews.image_views import (
    ImageDeleteView,
    ImageDetailView,
    ImageListView,
    ImageUpdateView,
    ImageUploadView,
    ImageSummaryView,
    ImageUploaderView,
)

from myapp.myviews.image_graph_views import (
    ImageGraphClassView,
    ImageGraphColorClassView,
    ImageTableColorClassView,
)

finalproject/myapp/templates/myapp/image/image_by_uploader.html
{% extends "myapp/core_base2.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="flex flex-col w-5/6 fixed right-0 top-14 h-[calc(100vh-3.5rem)] px-4 py-4 overflow-y-auto overflow-hidden" id="content">
    <div class="flex flex-col m-2 bg-white rounded-md p-4 shadow-md z-10 mb-48 pb-20">
        <div class="flex flex-row justify-between items-center mb-2">
            <div class="flex flex-col space-y-2">
                <h1 class="text-2xl font-bold text-gray-700">{{ title }}</h1>
            </div>
            <div class="flex flex-row space-x-2">
                <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700 space-x-2" onclick="window.history.back();">
                    <i class="fas fa-arrow-left"></i>
                    <span>Back</span>
                </button>
                <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700">
                    <i class="fas fa-ellipsis-v"></i>
                </button>
            </div>
        </div>
        <hr class="border-gray-200 mb-2">
        <div class="flex flex-col space-y-2">
            <!-- list Image Upload -->
            <div class="flex flex-row justify-between items-center">
                <div class="flex flex-row space-x-2">
                    <div class="flex flex-col space-y-1">
                        <h1 class="text-lg font-bold text-gray-700">Image Uploaded by {{ kwargs_uploader|capfirst }}</h1>
                        <p class="text-sm text-gray-500">Here is a list of images that have been uploaded. You can add, edit, or delete them.</p>
                    </div>
                </div>
                <div class="">
            <!-- dropdown filter -->
            <div class="flex flex-row space-x-2">
                <form class="flex flex-row justify-center items-center" method="GET">
                    <!-- input -->
                    <input type="text" class="block w-full text-sm text-slate-500 rounded-md file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-violet-50 file:text-violet-700 hover:file:bg-violet-100 " placeholder="Search..." name="search" value="{{ request.GET.search }}">
                    <!-- button search image -->
                    <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700 ml-2" type="submit">
                        <i class="fas fa-search"></i>
                        <span class="ml-2">Search</span>
                    </button>
                </form>
                <!-- button upload image -->
                <a class="flex flex-row justify-center items-center bg-blue-200 hover:bg-blue-300 rounded-md px-4 py-2 text-gray-700" href="{% url 'myapp:image_upload' %}">
                    <i class="fas fa-upload"></i>
                    <span class="ml-2">Upload</span>
                </a>
                <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" id="modalButton-1" aria-expanded="false" aria-haspopup="true" onclick="toggleModal(1)">
                    Filter
                    <!-- icon filter-->
                    <i class="fas fa-filter ml-2 mt-1"></i>
                </button>
            </div>
            <!-- account menu dropdown absolute hidden -->
            <div id="modal-1" class="absolute right-12 mt-2 w-auto h-auto min-w-[300px] rounded-md shadow-md bg-white ring-1 ring-black ring-opacity-5 py-4 z-10 px-4 hidden">
                <!-- account profile -->
                <div class="flex flex-col items-center justify-center">
                    <ul class="space-y-2 w-full mt-4">
                        <!-- filter by user -->
                        {% for uploader in uploaders %}
                        <a class="flex flex-row justify-between items-center space-x-2 hover:bg-fuchsia-200 rounded-md p-2 cursor-pointer" href="{% url 'myapp:image_uploader' uploader.name %}">
                            <div class="flex flex-row justify-center items-center space-x-2">
                                <i class="fas fa-user"></i>
                                <!-- change capitalize first letter -->
                                <span class="text-sm font-semibold">{{ uploader.name|capfirst }}</span>
                            </div>
                            <span class="text-sm font-semibold text-gray-500">({{ uploader.count }})</span>
                        </a>
                        {% endfor %} 
                     </ul>
                </div>
            </div>
        </div>
            </div>
            <!-- list Images Uploaded -->
            {% if images %}
            <div class="flex flex-row flex-wrap justify-center items-center space-x-2">
                <table class="table-auto w-full">
                    <thead>
                        <tr>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-check"></i>
                                <span class="ml-2">No</span>
                            </th>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-image"></i>
                                <span class="ml-2">Image</span>
                            </th>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-user"></i>
                                <span class="ml-2">Uploader</span>
                            </th>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-info-circle"></i>
                                <span class="ml-2">Information</span>
                            </th>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-calendar-alt"></i>
                                <span class="ml-2">Date</span>
                            </th>
                            <th class="px-2 py-1 text-xs border">
                                <i class="fas fa-cog"></i>
                                <span class="ml-2">Action</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for image in images %}
                        <tr>
                            <td class="border px-2 py-1 text-xs">{{ forloop.counter }}</td>
                            <td class="border px-2 py-1 text-xs flex flex-row justify-center items-center space-x-2">
                                <img src="{{ image.image.url }}" class="w-9 h-9 object-cover object-center rounded-md">
                                <a href="{{ image.image.url }}" class="text-xs text-blue-500 hover:text-blue-600">
                                    <i class="fas fa-external-link-alt"></i>
                                </a>
                            </td>
                            <td class="border px-2 py-1 text-xs">{{ image.uploader|capfirst }}</td>
                            <td class="border px-2 py-1 text-xs space-x-2">
                                <span class="px-2 py-1 rounded-md bg-blue-200 text-blue-700 text-xs">
                                     {{ image.width|intcomma }} x {{ image.height|intcomma }} px
                                </span>
                                <span class="px-2 py-1 rounded-md bg-orange-200 text-orange-700 text-xs">
                                     {{ image.size|filesizeformat }}
                                </span>
                                <span class="px-2 py-1 rounded-md bg-green-200 text-green-700 text-xs">
                                     {{ image.channel }} Ch
                                </span>
                                <span class="px-2 py-1 rounded-md bg-yellow-200 text-yellow-700 text-xs">
                                    {{ image.dpi }} dpi
                                </span>
                                <span class="px-2 py-1 rounded-md bg-purple-200 text-purple-700 text-xs">
                                    {{ image.color|capfirst }}
                                </span>
                            </td>
                            <td class="border px-2 py-1 text-xs">{{ image.created_at|naturaltime }}</td>
                            <td class="border px-2 py-1 text-xs">
                                <div class="flex flex-row space-x-2">
                                    <a class="flex flex-row justify-center items-center bg-blue-500 hover:bg-blue-600 rounded-md px-2 py-1 text-white" href="{% url 'myapp:image_update' image.id %}">
                                        <i class="fas fa-edit"></i>
                                        <span class="ml-2">Edit</span>
                                    </a>
                                    <a class="flex flex-row justify-center items-center bg-red-500 hover:bg-red-600 rounded-md px-2 py-1 text-white" href="{% url 'myapp:image_delete' image.id %}">
                                        <i class="fas fa-trash"></i>
                                        <span class="ml-2">Delete</span>
                                    </a>
                                    <a class="flex flex-row justify-center items-center bg-green-500 hover:bg-green-600 rounded-md px-2 py-1 text-white" href="{{ image.image.url }}" download>
                                        <i class="fas fa-download"></i>
                                        <span class="ml-2">Download</span>
                                    </a>
                                    <a class="flex flex-row justify-center items-center bg-gray-500 hover:bg-gray-600 rounded-md px-2 py-1 text-white" href="{% url 'myapp:image_detail' image.id %}">
                                        <i class="fas fa-eye"></i>
                                        <span class="ml-2">Detail</span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="flex flex-row justify-center items-center space-x-2">
                <div class="flex flex-col justify-center items-center space-y-2">
                    <i class="fas fa-images text-4xl text-gray-500"></i>
                    <span class="text-sm text-gray-500">No Images Uploaded</span>
                </div>
            </div>
            {% endif %}
            <!-- pagination with first, prev, next, last and number position end -->
            {% if is_paginated %}
            <div class="flex flex-row justify-between items-center space-x-2">
                <div class="flex flex-row space-x-2">
                    <span class="text-xs text-gray-500">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </div>
                <div class="flex flex-row space-x-2">
                    {% if page_obj.has_previous %}
                    <a class="text-xs flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700" href="?page=1&search={{ request.GET.search }}">
                        <i class="fas fa-angle-double-left"></i>
                    </a>
                    <a class="text-xs flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}">
                        <i class="fas fa-angle-left"></i>
                    </a>
                    {% endif %}
                    {% for page in page_obj.paginator.page_range %}
                    {% if page_obj.number == page %}
                    <a class="text-xs flex flex-row justify-center items-center bg-blue-200 hover:bg-blue-300 rounded-md px-4 py-2 text-gray-700" href="?page={{ page }}&search={{ request.GET.search }}">{{ page }}</a>
                    {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                    <a class="text-xs flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700" href="?page={{ page }}&search={{ request.GET.search }}">{{ page }}</a>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <a class="text-xs flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}">
                        <i class="fas fa-angle-right"></i>
                    </a>
                    <a class="text-xs flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}">
                        <i class="fas fa-angle-double-right"></i>
                    </a>
                    {% endif %}

                </div>
                <div class="flex flex-row space-x-2">
                    <span class="text-xs text-gray-500">Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} entries.</span>
                </div>
            </div>
            {% endif %}
            <!-- pagination with first, prev, next, last and number position end -->
        </div>
    </div>
</div>
{% endblock content %}

finalproject/myapp/templates/myapp/image/image_update.html
{% extends "myapp/core_base2.html" %}
{% load static %}

{% block content %}
<!-- content overflow -->
<div class="flex flex-col w-5/6 fixed right-0 top-14 h-[calc(100vh-3.5rem)] px-4 py-4 overflow-y-auto overflow-hidden" id="content">
    <div class="flex flex-col m-2 bg-white rounded-md p-4 shadow-md z-10 mb-40">
        <div class="flex flex-row justify-between items-center mb-2">
            <div class="flex flex-col space-y-2">
                <h1 class="text-2xl font-bold text-gray-700">{{ title }}</h1>
            </div>
            <div class="flex flex-row space-x-2">
                <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700 space-x-2" onclick="window.history.back();">
                    <i class="fas fa-arrow-left"></i>
                    <span>Back</span>
                </button>
                <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700">
                    <i class="fas fa-ellipsis-v"></i>
                </button>
            </div>
        </div>
        <hr class="border-gray-200 mb-2">
        <div class="flex flex-col space-y-2 w-full">
            <!-- Upload image for segmentations -->
            <div class="flex flex-row justify-between items-center">
                <div class="flex flex-row space-x-2">
                    <div class="flex flex-col space-y-1">
                        <h1 class="text-lg font-bold text-gray-700">Upload Image</h1>
                        <p class="text-sm text-gray-500">Upload an image to be segmented. The image will be resized to <span class="font-bold">512x512</span> pixels.</p>
                    </div>
                </div>
            </div>
            <!-- image form update preview  -->
            <div class="flex flex-row justify-start items-center space-x-4">
                <div class="flex flex-col space-y-1">
                    <h1 class="text-lg font-bold text-gray-700">Preview</h1>
                    <p class="text-sm text-gray-500">Preview of the image to be uploaded.</p>
                    <img src="/{{ form.image.value }}" class="w-64 h-64 object-cover object-center rounded-md shadow-md">
                </div>
                <div class="flex flex-col space-y-1">
                    <h1 class="text-lg font-bold text-gray-700">Preview Changes</h1>
                    <p class="text-sm text-gray-500">Preview of the image after changes.</p>
                    <img src="/{{ form.image.value }}" class="w-64 h-64 object-cover object-center rounded-md shadow-md" id="image-preview">
                </div>
            </div>
            <!-- message -->
            {% if messages %}
            <div class="flex flex-row justify-between items-center">
                <div class="flex flex-col space-y-1">
                    {% for message in messages %}
                    <p class="text-sm text-gray-500">{{ message }}</p>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            <!-- image upload form -->
            <form method='POST' enctype="multipart/form-data" class="flex flex-col space-y-2 w-full">
                {% csrf_token %}
                {{ form.as_table }}
                <button type="submit" class="flex flex-row justify-center items-center bg-blue-500 hover:bg-blue-600 rounded-md px-4 py-2 text-white">
                    <i class="fas fa-pencil-alt"></i>
                    <span class="ml-2">Update</span>
                </button>
            </form>
        </div>
    </div>
    <!-- image upload form end -->
</div>
{% endblock content %}
{% block scriptcustom %} 
<script>
    // image preview
    const imagePreview = document.getElementById('image-preview');
    const imageUpload = document.getElementById('id_image');
    imageUpload.addEventListener('change', function() {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.addEventListener('load', function() {
                imagePreview.setAttribute('src', this.result);
            });
            reader.readAsDataURL(file);
        } else {
            imagePreview.setAttribute('src', '/static/images/placeholder.png');
        }
    });
</script>
{% endblock scriptcustom %}