finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

finalproject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUpClassView.as_view(), name="signup"),
    path("signout/", views.SignOutClassView.as_view(), name="signout"),
    path("signin/", views.SignInClassView.as_view(), name="signin"),
    path(
        "segmentation/summary/",
        views.SegmentationSummaryClassView.as_view(),
        name="segmentation_summary",
    ),
    path(
        "segmentation/delete/<int:pk>/",
        views.SegmentationDeleteClassView.as_view(),
        name="segmentation_delete",
    ),
    path(
        "segmentation/detail/<int:pk>/",
        views.SegmentationDetailClassView.as_view(),
        name="segmentation_detail",
    ),
    path("segmentation/", views.SegmentationClassView.as_view(), name="segmentation"),
    path("setting/", views.SettingClassView.as_view(), name="setting"),
    path(
        "report/summary/", views.ReportSummaryClassView.as_view(), name="report_summary"
    ),
    path(
        "report/segmentation/",
        views.ReportSegmentationClassView.as_view(),
        name="report_segmentation",
    ),
    path(
        "report/export/report/",
        views.ReportExportReportClassView.as_view(),
        name="report_export_report",
    ),
    path(
        "report/export/image/<int:pk>/",
        views.ReportExportImageClassView.as_view(),
        name="report_export_image",
    ),
    path("report/", views.ReportClassView.as_view(), name="report"),
    path(
        "preference/setting/",
        views.PreferenceSettingClassView.as_view(),
        name="preference_setting",
    ),
    path("preference/", views.PreferenceClassView.as_view(), name="preference"),
    path(
        "manage/user/reset-password/<int:pk>/",
        views.ManageUserResetPasswordClassView.as_view(),
        name="manage_user_reset_password",
    ),
    path(
        "manage/user/group/edit/<int:pk>/",
        views.ManageUserGroupEditClassView.as_view(),
        name="manage_user_group_edit",
    ),
    path(
        "manage/user/edit/<int:pk>/",
        views.ManageUserEditClassView.as_view(),
        name="manage_user_edit",
    ),
    path(
        "manage/user/detail/<int:pk>/",
        views.ManageUserDetailClassView.as_view(),
        name="manage_user_detail",
    ),
    path(
        "manage/user/delete/<int:pk>/",
        views.ManageUserDeleteClassView.as_view(),
        name="manage_user_delete",
    ),
    path(
        "manage/user/add/",
        views.ManageUserAddClassView.as_view(),
        name="manage_user_add",
    ),
    path("manage/user/", views.ManageUsersClassView.as_view(), name="manage_user"),
    path(
        "image/uploader/<str:uploader>/",
        views.ImageUploaderView.as_view(),
        name="image_uploader",
    ),
    path("image/upload/", views.ImageUploadView.as_view(), name="image_upload"),
    path(
        "image/update/<int:pk>/", views.ImageUpdateView.as_view(), name="image_update"
    ),
    path("image/summary/", views.ImageSummaryView.as_view(), name="image_summary"),
    path(
        "image/table/color/",
        views.ImageTableColorClassView.as_view(),
        name="image_table_color",
    ),
    path(
        "image/graph/color/",
        views.ImageGraphColorClassView.as_view(),
        name="image_graph_color",
    ),
    path("image/graph/", views.ImageGraphClassView.as_view(), name="image_graph"),
    path(
        "image/delete/<int:pk>/", views.ImageDeleteView.as_view(), name="image_delete"
    ),
    path(
        "image/detail/<int:pk>/", views.ImageDetailView.as_view(), name="image_detail"
    ),
    path("image/", views.ImageListView.as_view(), name="image_list"),
    path("help/", views.HelpClassView.as_view(), name="help"),
    path("docs/", views.DocsClassView.as_view(), name="docs"),
    path("dashboard/", views.DashboardClassView.as_view(), name="dashboard"),
    path("contact/", views.ContactClassView.as_view(), name="contact"),
    path("blog/", views.BlogClassView.as_view(), name="blog"),
    path(
        "account/profile/",
        views.AccountProfileClassView.as_view(),
        name="account_profile",
    ),
    path(
        "account/<str:username>/update/",
        views.AccountUpdateClassView.as_view(),
        name="account_update",
    ),
    path(
        "account/<str:username>/change-password/",
        views.AccountChangePasswordClassView.as_view(),
        name="account_change_password",
    ),
    path("account/<str:username>/", views.AccountClassView.as_view(), name="account"),
    path("about/", views.AboutClassView.as_view(), name="about"),
    path("", views.IndexClassView.as_view(), name="index"),
]

finalproject/myapp/forms.py
from django import forms
from .models import Image
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError

# models User
from django.contrib.auth.models import User, Group

# models UserProfile
from myapp.models import UserProfile


class ManageUserGroupEditForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = User
        fields = []


class UserResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

        labels = {
            "username": "Username",
            "email": "Email",
        }


class UserForm(forms.ModelForm):
    bio = forms.CharField(label="Bio", required=False)
    phone_number = forms.CharField(label="Phone Number", required=False)
    address = forms.CharField(label="Address", required=False)
    date_of_birth = forms.DateField(label="Date of Birth", required=False)
    profile_pic = forms.ImageField(label="Profile Picture", required=False)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

        labels = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
        }


class UserChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        label="Old Password", widget=forms.PasswordInput(), required=True
    )
    new_password = forms.CharField(
        label="New Password", widget=forms.PasswordInput(), required=True
    )
    confirm_password = forms.CharField(
        label="Confirm New Password", widget=forms.PasswordInput(), required=True
    )

    class Meta:
        model = User
        fields = []

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get("old_password")
        cleaned_data["password"] = old_password
        return cleaned_data


class VisibleMultipleHiddenInput(forms.widgets.HiddenInput):
    def render(self, name, value, attrs=None, renderer=None):
        if not attrs:
            attrs = {}
        attrs["type"] = "hidden"  # Change the input type to 'hidden'
        return mark_safe(super().render(name, value, attrs, renderer))


class ImageForm(forms.ModelForm):
    def clean_image(self):
        image = self.cleaned_data.get("image")
        if not image:
            raise ValidationError(self.error_messages["image"])
        return image

    class Meta:
        model = Image
        fields = [
            "uploader",
            "image",
            "distance",
            "color",
        ]
        labels = {
            "uploader": "Uploader",
            "image": "Image",
            "distance": "Distance",
            "color": "Color",
        }
        widgets = {
            "uploader": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Uploader",
                }
            ),
            "image": forms.FileInput(
                attrs={
                    # tailwindcss
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Image",
                    "id": "id_image",
                    "accept": "image/*",
                }
            ),
            "distance": forms.NumberInput(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Distance",
                    "min": 0,
                    "max": 100,
                    "step": 1,
                }
            ),
            "color": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Color",
                    "data-live-search": "true",
                    "data-size": "5",
                }
            ),
        }
        allow_empty_file = False
        error_messages = {
            "uploader": {
                "required": "Uploader is required but hidden",
            },
            "image": {
                "required": "Image is required but hidden",
            },
        }

finalproject/myapp/views.py
from myapp.myviews.manage_views import (
    ManageClassView,
    ManageUsersClassView,
)

from myapp.myviews.manage_user_views import (
    ManageUserAddClassView,
    ManageUserDeleteClassView,
    ManageUserDetailClassView,
    ManageUserEditClassView,
    ManageUserResetPasswordClassView,
    ManageUserGroupEditClassView,
)

from myapp.myviews.report_views import (
    ReportClassView,
    ReportExportImageClassView,
    ReportExportReportClassView,
    ReportSegmentationClassView,
    ReportSummaryClassView,
)

from myapp.myviews.segmentation_views import (
    SegmentationClassView,
    SegmentationDetailClassView,
    SegmentationSummaryClassView,
    SegmentationDeleteClassView,
)

from myapp.myviews.system_views import (
    SignInClassView,
    SignOutClassView,
    SignUpClassView,
)

from myapp.myviews.preference_views import (
    PreferenceClassView,
    AboutClassView,
    BlogClassView,
    ContactClassView,
    PreferenceSettingClassView,
    HelpClassView,
    DocsClassView,
    SettingClassView,
    DashboardClassView,
    IndexClassView,
)

from myapp.myviews.account_views import (
    AccountChangePasswordClassView,
    AccountClassView,
    AccountUpdateClassView,
    AccountProfileClassView,
)

from myapp.myviews.image_views import (
    ImageDeleteView,
    ImageDetailView,
    ImageListView,
    ImageUpdateView,
    ImageUploadView,
    ImageSummaryView,
    ImageUploaderView,
)

from myapp.myviews.image_graph_views import (
    ImageGraphClassView,
    ImageGraphColorClassView,
    ImageTableColorClassView,
)

finalproject/myapp/templates/myapp/about.html
{% extends "myapp/core_base.html" %}
{% load static %}

{% block container %}
<div class="flex flex-col justify-center items-center">
    <!-- about card website information features -->
    <div class="bg-white shadow-md rounded-lg px-10 py-6 m-4 w-[600px]">
        <div class="flex justify-center md:justify-end -mt-16">
            <img class="w-20 h-20 object-cover rounded-full border-2 border-indigo-500 bg-white" src="{% static 'myapp/assets/author.png' %}">
        </div>
        <div>
            <h2 class="text-gray-800 text-3xl font-semibold mb-3">About Project</h2>
            <p class="text-1xl text-gray-600 text-justify indent-10">
                <span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">ALLIO</span> 
                is a platform that provides services to assist you in simulating image segmentation using the 
                <span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent"> Otsu Thresholding</span> dan 
                <span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">Sobel</span> algorithms. As an initial identification, you can choose one of these two methods to perform image segmentation.
            </p>
            <ul class="text-gray-600 text-justify mt-3 leading-7">
                <li><span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">K-Means</span> As an initial identification, you can choose one of these two methods to perform image segmentation.</li>
                <li><span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">Adapative Thresholding</span> is an algorithm used to convert an image into a binary image.</li>
            </ul>
        </div>
        <div class="flex justify-end mt-4">
            <a href="{% url 'myapp:index' %}" class="font-medium text-indigo-500">Back to Home</a>
        </div>
    </div>

</div>
{% endblock container %}

finalproject/myapp/templates/myapp/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static app_css %}">
</head>
<body>
    <div class="container-fluid mx-auto bg-red-200">
        <div class="flex flex-col items-center justify-center">
        <img src="{% static logo %}" alt="Logo" class="w-16">
        <h1 class="text-4xl font-bold text-center text-gray-700">{{ title }}</h1>
        <p class="text-xl text-center text-gray-700">{{ content }}</p>
        <div class="flex w-full">
            <div class="w-1/6 bg-gray-100">
                {% include 'myapp/snippets/navs.html' %}
            </div>
            <div class="w-5/6 bg-white">
                {% block container %}
            
                {% endblock container %}
            </div>
        </div>
        {% include 'myapp/snippets/footer.html' %}
        </div>
        
    </div>
    {% include 'myapp/snippets/scripts.html' %}
</body>
</html>

finalproject/myapp/templates/myapp/blog.html
{% extends "myapp/core_base.html" %}
{% load static %}

{% block container %}
<div class="flex flex-col justify-center items-center w-full">
    <!-- blog post -->
    <div class="w-full max-w-xs md:max-w-sm lg:max-w-4xl rounded overflow-hidden my-2 h-[500px] bg-white shadow-md">
        <div class=" px-8 pt-6 pb-4">
            <h1 class="text-2xl font-bold mb-2">Blog</h1>
            <p class="text-gray-700 text-base">Get the latest news and updates from our blog</p>
        </div>
        <!-- blog list post scrollable -->
        
    </div>
</div>
{% endblock container %}

finalproject/myapp/templates/myapp/contact.html
{% extends "myapp/core_base.html" %}
{% load static %}

{% block container %}
<div class="flex flex-col justify-center items-center">
    <!-- contact card website information author -->
    <div class="bg-white shadow-md rounded-lg px-10 py-6 m-4 w-[600px]">
        <div class="flex justify-center md:justify-end -mt-16">
            <img class="w-20 h-20 object-cover rounded-full border-2 border-indigo-500 bg-white" src="{% static 'myapp/assets/author.png' %}">
        </div>
        <div>
            <h2 class="text-gray-800 text-3xl font-semibold mb-3">Author</h2>
            <p class="text-gray-600">Name: <span class="text-gray-800 font-semibold">M. Anas Restuning Pamuji</span></p>
            <p class="text-gray-600">Email: <span class="text-gray-800 font-semibold">
                <a href="mailto:harryprost0@gmail.com">harryprost0@gmail.com</a>
            </span></p>
            <p class="text-gray-600">Github: <span class="text-gray-800 font-semibold">
                <a href="https//github.com/anasrestuning">github.com/anasrestuning</a>
            </span></p>
        </div>
        <div class="flex justify-end mt-4">
            <a href="{% url 'myapp:index' %}" class="font-medium text-indigo-500">Back to Home</a>
        </div>
    </div>
</div>
{% endblock container %}

finalproject/myapp/templates/myapp/core_base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% tailwind_css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,800;0,900;1,100;1,200;1,300;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static app_css %}">
</head>
<body class="font-poppins bg-gradient-to-tr from-red-400 via-slate-200 to-purple-400 h-screen">
    <div class="flex flex-col h-screen justify-between">
        <div class="flex flex-col justify-start items-center">
            {% include 'myapp/snippets/core/navbar.html' %}
        </div>
        <div class="flex flex-col justify-center items-center">
            {% block container %}
            
            {% endblock container %}
        </div>
        <div class="flex flex-col justify-center items-center">
            {% include 'myapp/snippets/core/footer.html' %}
        </div>
    </div>
    {% include 'myapp/snippets/scripts.html' %}
    {% load sweetify %}
    {% sweetify %}
    <!-- static nonce -->
    {% sweetify nonce="XYZ" %}

    <!-- from request -->
    {% sweetify nonce=request.csp_nonce %}
</body>
</html>

finalproject/myapp/templates/myapp/core_base2.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% tailwind_css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,800;0,900;1,100;1,200;1,300;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
</head>
<body class="font-poppins h-screen">
    <div class="flex flex-col h-screen justify-between">
        <div class="flex flex-col justify-start items-center top-0 fixed w-full z-10">
            {% include 'myapp/snippets/navbar.html' %}
        </div>
        <!-- fixed sidebar Menu and content overflow -->
        <div class="flex flex-col justify-center items-center">
            <!-- fixed sidebar Menu -->
            {% include 'myapp/snippets/sidebar.html' %}
            <!-- content overflow -->
            {% block content %} {% endblock content %}
            
        </div>
        <!-- footer top z-index -->
        <div class="flex flex-col justify-center items-center bg-white w-full fixed bottom-0">
            {% include 'myapp/snippets/footer.html' %}
        </div>
    </div>
    {% include 'myapp/snippets/scripts.html' %}
    {% block scriptcustom %} {% endblock scriptcustom %}
    {% block chartjs %} {% endblock chartjs %}
    <script text="text/javascript">
        function goBack() {
            window.history.back(); // Kembali ke halaman sebelumnya
        }
        function toggleMenu() {
            const menu = document.querySelector('#toogleMenu');
            menu.classList.toggle('hidden');
            // toogle content from 5/6 to 6/6
            const content = document.querySelector('#content');
            content.classList.toggle('w-5/6');
            content.classList.toggle('w-full');
            
        }

        function toogleAccountMenu() {
            const accountMenu = document.querySelector('#accountMenu');
            accountMenu.classList.toggle('hidden');
        }

        function toggleModal(id) {
            const modal = document.querySelector(`#modal-${id}`);
            modal.classList.toggle('hidden');
        }

        function toggleDropdown(id) {
            const dropdownMenu = document.querySelector(`#dropdown-menu-${id}`);
            const dropdownIcon = document.querySelector(`#dropdown-icon-${id}`);
            dropdownMenu.classList.toggle('hidden');
            dropdownIcon.classList.toggle('rotate-180');
        }

        function previewImage(event) {
            var reader = new FileReader();
            var imageField = document.querySelector('#image-field');
            var imagePreview = document.querySelector('#image-preview');
            var imagePreviewCount = document.querySelector('#image-preview-count');
            var imagePreviewName = document.querySelector('#image-preview-name');
            var imagePreviewSize = document.querySelector('#image-preview-size');
            var imagePreviewDimension = document.querySelector('#image-preview-dimension');

            reader.onload = function() {
                if (reader.readyState == 2) {
                    imagePreview.src = reader.result;
                    imageField.value = reader.result;
                }
            }

            if (imageField.files && imageField.files.length > 0) {
                reader.readAsDataURL(imageField.files[0]);
                // Change HTML content with the count of selected image files 0/1
                imagePreviewCount.innerHTML = `${imageField.files.length}/1`;
                // Change HTML content with the name of selected image files number of image files
                imagePreviewName.innerHTML = '';
                for (let i = 0; i < imageField.files.length; i++) {
                    oldName = imagePreviewName.innerHTML;
                    imagePreviewName.innerHTML = `${oldName} , ${imageField.files[i].name}`;
                }
                // jika panjang nama file melebihi 40 karakter
                if (imagePreviewName.innerHTML.length > 40) {
                    imagePreviewName.innerHTML = `${imagePreviewName.innerHTML.substring(0, 40)} ...`;
                }
                // Change HTML content with the size of selected image files number of image files ubah satuan ke MB
                imagePreviewSize.innerHTML = '';
                for (let i = 0; i < imageField.files.length; i++) {
                    oldSize = imagePreviewSize.innerHTML;
                    size = imageField.files[i].size / 1024 / 1024;
                    imagePreviewSize.innerHTML = `${oldSize} , ${size.toFixed(2)} MB`;
                }
                // jika panjang nama file melebihi 40 karakter
                if (imagePreviewSize.innerHTML.length > 40) {
                    imagePreviewSize.innerHTML = `${imagePreviewSize.innerHTML.substring(0, 40)} ...`;
                }

            } else {
                imagePreview.src = "{% static 'myapp/assets/author.png' %}";
                // Reset HTML content if no image is selected
                imagePreviewCount.innerHTML = `0/1`;
            }

        }
        // listen for change event on image field
        document.addEventListener('DOMContentLoaded', function() {
            // null check
            var imageField = document.querySelector('#image-field');
            if (imageField) {
                imageField.addEventListener('change', previewImage);
            }
        });

    </script>
</body>
</html>

finalproject/myapp/templates/myapp/docs.html
{% extends "myapp/core_base2.html" %}
{% load static %}

{% block content %}
<!-- content overflow -->
<div class="flex flex-col w-5/6 fixed right-0 top-14 h-[calc(100vh-3.5rem)] px-4 py-4 overflow-y-auto overflow-hidden" id="content">
    <div class="flex flex-col m-2 bg-white rounded-md p-4 shadow-md z-10">
        <div class="flex flex-row justify-between items-center mb-2">
            <div class="flex flex-col space-y-2">
                <h1 class="text-2xl font-bold text-gray-700">{{ title }}</h1>
            </div>
            <div class="flex flex-row space-x-2">
                <button class="flex flex-row justify-center items-center bg-gray-200 hover:bg-gray-300 rounded-md px-4 py-2 text-gray-700">
                    <i class="fas fa-ellipsis-v"></i>
                </button>
            </div>
        </div>
        <hr class="border-gray-200 mb-2">
        <div class="flex flex-col space-y-2">  
        </div>
    </div>
</div>
{% endblock content %}

finalproject/myapp/templates/myapp/index.html
{% extends "myapp/core_base.html" %}
{% load static %}

{% block container %}

<div class="flex flex-col justify-center items-center">
    <div class="flex flex-col justify-center items-center gap-4">
        <h1 class="text-5xl font-bold text-gray-900">Welcome to
            ALL<span class="bg-gradient-to-t from-blue-500 to-teal-400 bg-clip-text text-transparent">IO</span>
        </h1>
        {% if messages %}
        <div class="flex flex-col justify-center items-center gap-4">
            {% for message in messages %}
            <div class="bg-{{ message.tags }}-400 text-white px-4 py-2 rounded mx-2">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <p class="text-1xl text-gray-600 px-24 text-center">
            ALLIO is a platform that provides services to help you simulate image segmentation using 
            <span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">Otsu Thresholding </span>dan 
            <span class="bg-gradient-to-t from-red-500 to-red-400 bg-clip-text text-transparent">Sobel</span> algorithms. As an initial identification, you can choose one of the two methods to perform image segmentation.
        </p>
        <div class="flex flex-row justify-center items-center">
            <a href="{% url 'myapp:signin' %}" class="bg-blue-400 text-white px-4 py-2 rounded mx-2 hover:bg-blue-600">
                <i class="fas fa-sign-in-alt"></i>
                <span class="ml-2">Sign In</span>
            </a>
            <a href="{% url 'myapp:signup' %}" class="bg-blue-400 text-white px-4 py-2 rounded mx-2 hover:bg-blue-600">
                <i class="fas fa-user-plus"></i>
                <span class="ml-2">Sign Up</span>
            </a>
        </div>
    </div>
</div>
{% endblock container %}