finalproject/finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
]

finalproject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("signup/", views.SignUpClassView.as_view(), name="signup"),
    path("signout/", views.SignOutClassView.as_view(), name="signout"),
    path("signin/", views.SignInClassView.as_view(), name="signin"),
    path(
        "segmentation/summary/",
        views.SegmentationSummaryClassView.as_view(),
        name="segmentation_summary",
    ),
    path(
        "segmentation/delete/<int:pk>/",
        views.SegmentationDeleteClassView.as_view(),
        name="segmentation_delete",
    ),
    path(
        "segmentation/detail/<int:pk>/",
        views.SegmentationDetailClassView.as_view(),
        name="segmentation_detail",
    ),
    path("segmentation/", views.SegmentationClassView.as_view(), name="segmentation"),
    path("setting/", views.SettingClassView.as_view(), name="setting"),
    path(
        "report/summary/", views.ReportSummaryClassView.as_view(), name="report_summary"
    ),
    path(
        "report/segmentation/",
        views.ReportSegmentationClassView.as_view(),
        name="report_segmentation",
    ),
    path(
        "report/export/report/",
        views.ReportExportReportClassView.as_view(),
        name="report_export_report",
    ),
    path(
        "report/export/image/<int:pk>/",
        views.ReportExportImageClassView.as_view(),
        name="report_export_image",
    ),
    path("report/", views.ReportClassView.as_view(), name="report"),
    path(
        "preference/setting/",
        views.PreferenceSettingClassView.as_view(),
        name="preference_setting",
    ),
    path("preference/", views.PreferenceClassView.as_view(), name="preference"),
    path(
        "manage/user/reset-password/<int:pk>/",
        views.ManageUserResetPasswordClassView.as_view(),
        name="manage_user_reset_password",
    ),
    path(
        "manage/user/group/edit/<int:pk>/",
        views.ManageUserGroupEditClassView.as_view(),
        name="manage_user_group_edit",
    ),
    path(
        "manage/user/edit/<int:pk>/",
        views.ManageUserEditClassView.as_view(),
        name="manage_user_edit",
    ),
    path(
        "manage/user/detail/<int:pk>/",
        views.ManageUserDetailClassView.as_view(),
        name="manage_user_detail",
    ),
    path(
        "manage/user/delete/<int:pk>/",
        views.ManageUserDeleteClassView.as_view(),
        name="manage_user_delete",
    ),
    path(
        "manage/user/add/",
        views.ManageUserAddClassView.as_view(),
        name="manage_user_add",
    ),
    path("manage/user/", views.ManageUsersClassView.as_view(), name="manage_user"),
    path(
        "image/uploader/<str:uploader>/",
        views.ImageUploaderView.as_view(),
        name="image_uploader",
    ),
    path("image/upload/", views.ImageUploadView.as_view(), name="image_upload"),
    path(
        "image/update/<int:pk>/", views.ImageUpdateView.as_view(), name="image_update"
    ),
    path("image/summary/", views.ImageSummaryView.as_view(), name="image_summary"),
    path(
        "image/table/color/",
        views.ImageTableColorClassView.as_view(),
        name="image_table_color",
    ),
    path(
        "image/graph/color/",
        views.ImageGraphColorClassView.as_view(),
        name="image_graph_color",
    ),
    path("image/graph/", views.ImageGraphClassView.as_view(), name="image_graph"),
    path(
        "image/delete/<int:pk>/", views.ImageDeleteView.as_view(), name="image_delete"
    ),
    path(
        "image/detail/<int:pk>/", views.ImageDetailView.as_view(), name="image_detail"
    ),
    path("image/", views.ImageListView.as_view(), name="image_list"),
    path("help/", views.HelpClassView.as_view(), name="help"),
    path("docs/", views.DocsClassView.as_view(), name="docs"),
    path("dashboard/", views.DashboardClassView.as_view(), name="dashboard"),
    path("contact/", views.ContactClassView.as_view(), name="contact"),
    path("blog/", views.BlogClassView.as_view(), name="blog"),
    path(
        "account/profile/",
        views.AccountProfileClassView.as_view(),
        name="account_profile",
    ),
    path(
        "account/<str:username>/update/",
        views.AccountUpdateClassView.as_view(),
        name="account_update",
    ),
    path(
        "account/<str:username>/change-password/",
        views.AccountChangePasswordClassView.as_view(),
        name="account_change_password",
    ),
    path("account/<str:username>/", views.AccountClassView.as_view(), name="account"),
    path("about/", views.AboutClassView.as_view(), name="about"),
    path("", views.IndexClassView.as_view(), name="index"),
]

finalproject/myapp/forms.py
from django import forms
from .models import Image
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError

# models User
from django.contrib.auth.models import User, Group

# models UserProfile
from myapp.models import UserProfile


class ManageUserGroupEditForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = User
        fields = []


class UserResetPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
        ]

        labels = {
            "username": "Username",
            "email": "Email",
        }


class UserForm(forms.ModelForm):
    bio = forms.CharField(label="Bio", required=False)
    phone_number = forms.CharField(label="Phone Number", required=False)
    address = forms.CharField(label="Address", required=False)
    date_of_birth = forms.DateField(label="Date of Birth", required=False)
    profile_pic = forms.ImageField(label="Profile Picture", required=False)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

        labels = {
            "username": "Username",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
        }


class UserChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        label="Old Password", widget=forms.PasswordInput(), required=True
    )
    new_password = forms.CharField(
        label="New Password", widget=forms.PasswordInput(), required=True
    )
    confirm_password = forms.CharField(
        label="Confirm New Password", widget=forms.PasswordInput(), required=True
    )

    class Meta:
        model = User
        fields = []

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get("old_password")
        cleaned_data["password"] = old_password
        return cleaned_data


class VisibleMultipleHiddenInput(forms.widgets.HiddenInput):
    def render(self, name, value, attrs=None, renderer=None):
        if not attrs:
            attrs = {}
        attrs["type"] = "hidden"  # Change the input type to 'hidden'
        return mark_safe(super().render(name, value, attrs, renderer))


class ImageForm(forms.ModelForm):
    def clean_image(self):
        image = self.cleaned_data.get("image")
        if not image:
            raise ValidationError(self.error_messages["image"])
        return image

    class Meta:
        model = Image
        fields = [
            "uploader",
            "image",
            "distance",
            "color",
        ]
        labels = {
            "uploader": "Uploader",
            "image": "Image",
            "distance": "Distance",
            "color": "Color",
        }
        widgets = {
            "uploader": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Uploader",
                }
            ),
            "image": forms.FileInput(
                attrs={
                    # tailwindcss
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Image",
                    "id": "id_image",
                    "accept": "image/*",
                }
            ),
            "distance": forms.NumberInput(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Distance",
                    "min": 0,
                    "max": 100,
                    "step": 1,
                }
            ),
            "color": forms.Select(
                attrs={
                    "class": "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
                    "placeholder": "Color",
                    "data-live-search": "true",
                    "data-size": "5",
                }
            ),
        }
        allow_empty_file = False
        error_messages = {
            "uploader": {
                "required": "Uploader is required but hidden",
            },
            "image": {
                "required": "Image is required but hidden",
            },
        }

finalproject/myapp/views.py
from myapp.myviews.manage_views import (
    ManageClassView,
    ManageUsersClassView,
)

from myapp.myviews.manage_user_views import (
    ManageUserAddClassView,
    ManageUserDeleteClassView,
    ManageUserDetailClassView,
    ManageUserEditClassView,
    ManageUserResetPasswordClassView,
    ManageUserGroupEditClassView,
)

from myapp.myviews.report_views import (
    ReportClassView,
    ReportExportImageClassView,
    ReportExportReportClassView,
    ReportSegmentationClassView,
    ReportSummaryClassView,
)

from myapp.myviews.segmentation_views import (
    SegmentationClassView,
    SegmentationDetailClassView,
    SegmentationSummaryClassView,
    SegmentationDeleteClassView,
)

from myapp.myviews.system_views import (
    SignInClassView,
    SignOutClassView,
    SignUpClassView,
)

from myapp.myviews.preference_views import (
    PreferenceClassView,
    AboutClassView,
    BlogClassView,
    ContactClassView,
    PreferenceSettingClassView,
    HelpClassView,
    DocsClassView,
    SettingClassView,
    DashboardClassView,
    IndexClassView,
)

from myapp.myviews.account_views import (
    AccountChangePasswordClassView,
    AccountClassView,
    AccountUpdateClassView,
    AccountProfileClassView,
)

from myapp.myviews.image_views import (
    ImageDeleteView,
    ImageDetailView,
    ImageListView,
    ImageUpdateView,
    ImageUploadView,
    ImageSummaryView,
    ImageUploaderView,
)

from myapp.myviews.image_graph_views import (
    ImageGraphClassView,
    ImageGraphColorClassView,
    ImageTableColorClassView,
)

finalproject/myapp/templates/myapp/snippets/footer.html
<!-- text footer justify end -->
<footer class=" text-center py-4  shadow-md w-full">
    <div class="container mx-auto px-4">
        <div class="flex flex-wrap items-center justify-center md:justify-between">
            <div class="w-full md:w-4/12 px-4">
                <div class="text-sm text-gray-600 py-1 text-left">
                    © 2023 <a href="https://www.anansrestuning.com" class="text-gray-600 hover:text-gray-900">Anas Restuning</a>. All rights reserved.
                </div>
            </div>
            <div class="w-full md:w-8/12 px-4">
                <ul class="flex flex-wrap list-none md:justify-end  justify-center">
                    <li>
                        <a href="https://www.anansrestuning.com" class="text-gray-700 hover:text-gray-900 text-sm block py-1 px-3">Anas Restuning</a>
                    </li>
                    <li>
                        <a href="{% url 'myapp:about' %}"
                        class="text-gray-700 hover:text-gray-900 text-sm block py-1 px-3">About Us</a>
                    </li>
                    <li>
                        <a href="https://www.anansrestuning.com/" target="_blank"
                        class="text-gray-700 hover:text-gray-900 text-sm block py-1 px-3">Blog</a>
                    </li>
                    <li>
                        <a href="{% url 'myapp:contact' %}"
                        class="text-gray-700 hover:text-gray-900 text-sm block py-1 px-3">Contact Us</a>
                    </li>
                    <li>
                        <a href="http://www.github.com/anansrestuning" 
                        class="text-gray-700 hover:text-gray-900 text-sm block py-1 px-3">Github</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

finalproject/myapp/templates/myapp/snippets/modal.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% tailwind_css %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    
    <link rel="stylesheet" href="{% static app_css %}">
</head>
<body class="font-inter bg-gray-100">
    <button class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none cursor-pointer open-modal" id="open-modal">
        Open Modal
    </button>
    <div class="h-screen w-full fixed left-0 top-0 hidden justify-center items-center bg-gray-900 bg-opacity-50 show-modal" id="show-modal">
        <!-- modal -->
        <div class="bg-white rounded-md shadow-md w-96">
            <!-- modal header -->
            <div class="flex justify-between items-center px-4 py-2 border-b border-gray-200">
                <h3 class="text-lg font-semibold text-gray-700">Modal Title</h3>
                <button class="text-gray-600 focus:outline-none close-modal">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <!-- modal body -->
            <div class="px-4 py-2">
                <p class="text-sm text-gray-700">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, voluptates. Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum, voluptates.
                </p>
            </div>
            <!-- modal footer -->
            <div class="flex justify-end items-center w-full px-4 py-2 bg-gray-100 rounded-b-md">
                <a class="px-4 py-2 bg-red-300 text-red-700 rounded-md hover:bg-red-400 focus:outline-none cursor-pointer close-modal" id="close-modal">
                    <i class="fas fa-times"></i> Cancel
                </a>
                <a class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none cursor-pointer ml-2">
                    <i class="fas fa-check"></i> Ok
                </a>
            </div>
        </div>
    </div>
    <script type="text/javascript" >
        const openModal = document.querySelector('.open-modal');
        const showModal = document.querySelector('.show-modal');
        const closeModal = document.querySelectorAll('.close-modal');
        
        openModal.addEventListener('click', () => {
            showModal.classList.remove('hidden');
            showModal.classList.add('flex');
        });

        closeModal.forEach((btn) => {
            btn.addEventListener('click', () => {
                showModal.classList.add('hidden');
                showModal.classList.remove('flex');
            });
        });
        
    </script>
</body>
</html>

finalproject/myapp/templates/myapp/snippets/navbar.html
{% load static %}
<header class="bg-white shadow-md w-full">
    <nav class="flex items-center justify-between flex-wrap w-94% mx-auto py-1">
        <div class="flex flex-row">
            <!-- icon menu -->
            <div class="flex items-center flex-shrink-0 text-gray-800 ml-6">
                <button id="menu-toggle" class="flex items-center px-3 py-2 border border-gray-300 shadow-sm rounded-md hover:text-gray-900 hover:border-gray-900 appearance-none focus:outline-none text-gray-700" onclick="toggleMenu()">
                    <i class="fas fa-bars"></i>
                </button>
            </div>
            <a class="text-2xl font-bold px-4 py-2" href="{% url 'myapp:index' %}">
                ALL<span class="bg-gradient-to-t from-blue-500 to-teal-400 bg-clip-text text-transparent">IO</span>
            </a>
        </div>
        <div class="">
            <!-- account -->
            <div>
                <button type="button" class="inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mr-2" id="accountMenuButton" aria-expanded="false" aria-haspopup="true" onclick="toogleAccountMenu()">
                    Account
                    <i class="fas fa-chevron-down ml-4 mt-1"></i>
                </button>
            </div>
            <!-- account menu dropdown absolute hidden -->
            <div id="accountMenu" class="absolute right-2 mt-2 w-auto h-auto min-w-[300px] rounded-md shadow-md bg-white ring-1 ring-black ring-opacity-5 py-4 z-10 px-4 hidden">
                <!-- account profile -->
                <div class="flex flex-col items-center justify-center">
                    <div class="flex flex-row justify-between space-x-2">
                        <div>
                            <img class="w-16 h-16 rounded-full object-cover border-2 border-gray-300" alt="profile" src="{% if request.user.userprofile.profile_pic %}{{ request.user.userprofile.profile_pic.url }}{% else %}{% static 'myapp/assets/author.png' %}{% endif %}">
                        </div>
                        <div>
                            <h1 class="text-lg font-bold mt-2">{{ request.user.first_name|title }} {{ request.user.last_name|title }}</h1>
                            <h2 class="text-sm text-gray-500">
                                {% if request.user.is_superuser %}
                                    <i class="fas fa-user-shield text-teal-500 mr-2"></i>
                                    <span class="text-teal-500">Admin</span>
                                {% else %}
                                    <i class="fas fa-user text-teal-500 mr-2"></i>
                                    <span class="text-teal-500">User</span>
                                {% endif %}
                            </h2>
                        </div>
                    </div>
                    <!-- account menu -->
                    <ul class="space-y-2 w-full mt-4">
                        <li class="flex flex-row justify-between items-center space-x-2 hover:bg-teal-200 rounded-md p-2 cursor-pointer">
                            <div>
                                <i class="fas fa-user-circle text-teal-500 mr-2"></i>
                                <a href="{% url 'myapp:account_profile' %}" class="text-gray-500 hover:text-gray-900">
                                    Profile
                                </a>
                            </div>
                        </li>
                        <hr class="border-gray-200">
                        <li class="flex flex-row justify-between items-center space-x-2 hover:bg-teal-200 rounded-md p-2 cursor-pointer">
                            <div>
                                <i class="fas fa-cog text-teal-500 mr-2"></i>
                                <a href="{% url 'myapp:setting' %}" class="text-gray-500 hover:text-gray-900">
                                    Settings
                                </a>
                            </div>
                        </li>
                        <hr class="border-gray-200">
                        <li class="flex flex-row justify-between items-center space-x-2 hover:bg-teal-200 rounded-md p-2 cursor-pointer">
                            <div>
                                <i class="fas fa-sign-out-alt text-teal-500 mr-2"></i>
                                <a href="{% url 'myapp:signout' %}" class="text-gray-500 hover:text-gray-900">
                                    Sign out
                                </a>
                            </div>
                        </li>
                        <hr class="border-gray-200">
                     </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

finalproject/myapp/templates/myapp/snippets/scripts.html
{% load static %}
<script src="{% static app_js %}"></script>

finalproject/myapp/templates/myapp/snippets/sidebar.html
<div class="flex-1 flex-col w-1/6 fixed left-0 top-14 h-[calc(100vh-3.5rem)] px-2 py-4 shadow overflow-y-auto overflow-hidden no-scrollbar mb-96" id="toogleMenu">
    <!-- sidebar Menu menu list with icons and text dropdown -->
    <ul class="space-y-2">
    {% for menu in menus %}
        <li class="flex flex-row justify-between items-center space-x-2 hover:bg-black-200 rounded-md p-2 cursor-pointer" onclick="toggleDropdown('{{ menu.id }}')">
            <div>
                <i class="{{ menu.icon }} text-black-700 text-lg mr-2"></i>
                {% if menu.url == "" %}
                <span class="text-gray-700 hover:text-gray-900" target="_blank">
                    {{ menu.name }}
                </span>
                {% else %}
                <a href="{{ menu.url }}" class="text-gray-700 hover:text-gray-900">
                    {{ menu.name }}
                </a>
                {% endif %}
            </div>
            <!-- dropdown menu -->
            {% if menu.submenus %}
            <div>
                <i class="fas fa-chevron-down first-letter:text-gray-500 ml-auto rotate-180" id="dropdown-icon-{{ menu.id }}"></i>
            </div>
            {% endif %}
        </li>
        <hr class="border-gray-200">
        <!-- dropdown menu list with icons and text -->
        {% if menu.submenus %}
        <ul id="dropdown-menu-{{ menu.id }}" class="flex-col space-y-2 pl-4 py-2 hidden" >
            {% for submenu in menu.submenus %}
            <li class="flex flex-row justify-between items-center space-x-2 hover:bg-black-200 rounded-md p-2 cursor-pointer">
                <div>
                    <i class="{{ submenu.icon }} text-black-700 text-lg mr-2"></i>
                    <a href="{{ submenu.url }}" class="text-gray-700 hover:text-gray-900" {% if submenu.id == 'blog' %} target="_blank" {% endif %}>
                        {{ submenu.name }}
                    </a>
                </div>
            </li>
            {% endfor submenu %}
        </ul>
        {% endif %}
    {% endfor menu %}
    </ul>
</div>